---
- name: Clone backend repository
  git:
    repo: "{{ github_repo }}"
    dest: "{{ project_dir }}"
  tags: ['backend']

- name: Deploy backend application
  block:
    - name: Start backend container
      docker_compose:
        project_src: "{{ project_dir }}"
        service: "yolo-web-backend"
        state: present
        restarted: yes
        pull: yes
        remove_orphans: yes
  tags: ['backend']
