---
- name: Install Docker
  block:
    - name: Update apt repository
      apt:
        update_cache: yes

    - name: Install required packages
      apt:
        name: ['apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common']
        state: present

    - name: Add Docker's official GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
        state: present

    - name: Install Docker CE
      apt:
        name: docker-ce
        state: latest

    - name: Install Docker Compose
      get_url:
        url: https://github.com/docker/compose/releases/download/1.29.2/docker-compose-`uname -s`-`uname -m`
        dest: /usr/local/bin/docker-compose
        mode: '0755'

    - name: Ensure Docker service is running
      service:
        name: docker
        state: started
        enabled: yes
  tags: ['docker']

- name: Run MongoDB container
  docker_compose:
    project_src: "{{ project_dir }}"
    service: "yolo-web-mongodb"
    state: present
    restarted: yes
    pull: yes
  tags: ['db']






- name: Run MongoDB container
  docker_compose:
    project_src: "{{ project_dir }}"
    service: "yolo-web-mongodb"
    state: present
    restar

- name: Run MongoDB container
 