---
- name: Deploy YOLO Node.js application with MongoDB
  hosts: all
  become: yes

  vars_files:
    - group_vars/all.yml

  pre_tasks:
    - name: Install Git
      apt:
        name: git
        state: present

  roles:
    - { role: mongodb, tags: ['db'] }
    - { role: frontend, tags: ['frontend'] }
    - { role: backend, tags: ['backend'] }






rroles:
    - { role: mongodb, tags: ['db'] }
    