apiVersion: apps/v1
kind: Deployment
metadata:
  name: yolo-backend
spec:
  selector:
    matchLabels:
      app: yolo-backend
  template:
    metadata:
      labels:
        app: yolo-backend
    spec:
      containers:
      - name: yolo-backend
        image: beniye/yolo-web-backend
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000
        env:
          - name: MONGODB_URI
            valueFrom:
              configMapKeyRef:
                name: mongo-config
                key: MONGODB_URI
---

apiVersion: v1
kind: Service
metadata:
  name: yolo-backend-service
spec:
  type: LoadBalancer # This line specifies the type of service as LoadBalancer
  selector:
    app: yolo-backend
  ports:
  - port: 5000
    targetPort: 5000
